### ISSUE TITLE
Query

### ISSUE THREAD

**Issue by simon-p-r** [dotnil/ssh-config#1]
Hi

Great module however what is the length property for and can the object keys be the name of host rather than the index number?

Thanks
Simon

**Comment by dotnil** [comment]
The length property is for looping Hosts. So to find the Host section, you can use an old fashioned for loop:

```js
for (var i = 0, len = config.length; i < len; i++) {
  var host = config[i]
  if (host.Host === theHostYouWant) {
    dealWith(host)
  }
}
```

By `name of host` you mean Host or HostName?

**Comment by simon-p-r** [comment]
You can avoid setting the length as you can loop through the object keys like so;

````js
var keys = Object.keys(config);
for (var i = 0,  i < keys.length; i++) {
  var host = keys[i]
  if (host.Host === theHostYouWant) {
    dealWith(host)
  }
}
````

However to find the relevant host you would need to set top level keys of object to the name of host, see this example config and the resulting object;

````js
Host server1
     HostName server1.com
     User admin
     Port 22
     IdentityFile /path/to/key
Host server2
     HostName server2.com
     User admin
     Port 22
     IdentityFile /path/to/key
````
The object would look like this

````js
var config = {
    server1: {
        HostName: 'server1.com',
        User: 'admin',
        Port: 22,
        IdentityFile: 'path/to/key'  
    },
    server2: {
        HostName: 'server2.com',
        User: 'admin',
        Port: 22,
        IdentityFile: 'path/to/key'      
    }
};
````
Are you willing to make this change?

**Comment by dotnil** [comment]
That'll break current API. Would you give me a couple of hours to consider about it?

**Comment by simon-p-r** [comment]
Yes sure

**Comment by dotnil** [comment]
Sorry Simon, I think I'll stick with current structure.

The numeric properties and the `.length` were added because these are just sections within the parsed ssh config. And according to the [man page of ssh_config](http://www.openbsd.org/cgi-bin/man.cgi/OpenBSD-current/man5/ssh_config.5?query=ssh_config&arch=i386), both `Host` and `Match` can start new sections. 

The advantage of current structure is that it will retain the original structure of the ssh config text passed in. Given some ssh config like below:

```
IdentityFile ~/.ssh/id_rsa

Host *
  User nil

Host laputa
  User gulliver
  ForwardAgent true
``` 

If we parse it, then stringify the returned object, the result will be consistent with the original. Especially if the ssh config is long and has duplicated Host sections. 


I guess instead of an data structure change, a config matcher is the true feature you gonna need. Will your use case looks like below:

```
var sshConfig = require('ssh-config')

var config = sshConfig.parse(fs.readFileSync('~/.ssh/config'))
var settings = config.match('laputa.com')

// and settings will be an Object looks like:
//
//  {
//    IdentityFile: '~/.ssh/id_rsa',
//    Host: 'laputa.com',
//    User: 'gulliver',
//    ForwardAgent: true
//  }
```

**Comment by dotnil** [comment]
And about `.length`. If an enumerable length property were confusing, I can just hide it via `Object.defineProperty`, which is the same way I'm gonna use to provide the `.match` method.

**Comment by simon-p-r** [comment]
No problem I have spent some time reading more about config file structure (I only use the host part currently) .  Your suggested api  where you are returned the relevant host from the parsed object with match would work very well. :+1:

**Comment by dotnil** [comment]
Great. I'm on it.

**Comment by simon-p-r** [comment]
Cheers Jake

**Comment by simon-p-r** [comment]
I have pulled the add-query branch down and cannot get query to work correctly

**Comment by dotnil** [comment]
Can you provide more information?

**Comment by simon-p-r** [comment]
See this snippet

````js
var sshConfig = require('ssh-config');
var path = require('path');
var fs = require('fs');


var directory = path.join(process.env.HOME || process.env.USERPROFILE, '.ssh', 'config');

var results = fs.readFileSync(directory, 'utf8');

var parsed = sshConfig.parse(results);

var test = parsed.query('example1');
console.log(test);
````

It prints as an object of the first entry from config file and does not match the host called example1

````js
Host example
     HostName example.com
     User root
     Port 22
     IdentityFile /path/to/key
Host example1
     HostName example1
     User user
     Port 15
     IdentityFile another/path/to/keyfile

**Comment by dotnil** [comment]
Confirmed. Nice catch!

**Comment by dotnil** [comment]
@simon-p-r I've pushed a new commit in add-query branch. I believe this is fixed now.

Besides, what do you consider about current behaviour of `.query`? I use ssh-config in a deployer script myself. The most use cases about the parsed config data is to query some host and get relative ssh parameters about that host. So I implemented `.query` this way. 

If that's not exactly what you need, please let me know.

**Comment by dotnil** [comment]
If `.query` suffices, I'll merge and release 0.2.0 now.

**Comment by simon-p-r** [comment]
I have tried again however it still returns the incorrect entry.  I will write some tests on my forked repo to show you want I thought query api would be.

**Comment by simon-p-r** [comment]
I have added a test and a new test file which breaks the query method as it fails on port parsing

**Comment by dotnil** [comment]
Nice. I've checked out your code and looked inside. Your tests are based on an old version of add-query branch. The commit that fixes this issue is missed https://github.com/dotnil/ssh-config/commit/c71ffd4f8405df60b011d029cf4a66b2993d91e4

**Comment by simon-p-r** [comment]
Ok I have pulled that in and it appears to work very well, I like the fact it merges other parsed config into returned object - that is very clever!  Look forward to using this excellent module in my project :+1:
