### ISSUE TITLE
parse/stringify does not handle lack of new line at EOF

### ISSUE THREAD

**Issue by jerrosenberg** [dotnil/ssh-config#15]
If parsed config has no trailing new line, and you append a new config, and stringify it, there is no new line inserted between the original entry and the new entry.

Example:
```
const SSHConfig = require('ssh-config');

const config = SSHConfig.parse(`
Host test
  HostName example.com`);

config.append({
  Host: 'test2',
  HostName: 'example.com'
});

console.log(SSHConfig.stringify(config));
```

The output is:
```

Host test
  HostName google.comHost test2
  HostName microsoft.com


```

This makes both entries invalid.

**Comment by dotnil** [comment]
@jerrosenberg Thanks for your report. I've added your example into test and fixed the issue. 1.1.4 will be published soon.
