### ISSUE TITLE
Stringify issue

### ISSUE THREAD

**Issue by simon-p-r** [dotnil/ssh-config#4]
Hi

Sorry to be a pain however when I try to configure the returned config object I cannot set properties.  If a set method could be exposed it would help adding objects so that they can be stringified afterwards. Maybe it would need to automatically add the index based an object being passed to it.  See an example below;

````js

var config = require('ssh-config');
var data = {
    Host: 'test',
    HostName: 'localhost',
    User: 'centos',
    Port: 2000,
    IdentityFile: 'path/to/key/file'
}

var result = config.set(data);

console.log(result);

//result now contains the data object which can be stringified so it can be written out to file.
````

Also when I use stringify method it leaves a leading white space on the very first line.

Once again thanks for this excellent module.

Simon

**Comment by dotnil** [comment]
The fastest way to do it would be something like: 

```js
config[config.length] = {
    Host: 'test',
    HostName: 'localhost',
    User: 'centos',
    Port: 2000,
    IdentityFile: 'path/to/key/file'
}
```

It behaves exactly like  `config.append(data)`. But to change existing section, you still need to find it first. Since `.query` is for hosts configuration querying, I think a method like `.host` or `.find` will be necessary:

```js
config.host('example*')
config.host('example1')

// In the future if Match shall be supported. 
// But truth be told, I'm not familiar with it. It seems that the ssh command on Mac does not support Match
config.match('host', 'example*')
```

Then you can:

```js
var section = config.host('*')  // default configurations
section.IdentityFile = 'path/to/key/file'

// or if you prefer something like jQuery.extend
extend(section, {
    User: 'centos',
    Port: 2000,
    IdentityFile: 'path/to/key/file'
})
```

What do you think about it?

Also, about the stringify bug, I'll see to it tomorrow. It's nearly eleven pm. here (GMT +8).

**Comment by simon-p-r** [comment]
I have used the config.length to append to object, however I think and find and replace should also be possible.  One thing for safety is to ensure that there are no duplicate sections in object when appending to object as this could potentially write out an invalid config file when stringified.

**Comment by simon-p-r** [comment]
Ok when I use stringify using the config.length it writes this to file

````JS 
2 [object Object]

Host server1
     HostName server1.com
     User admin
     Port 22
     IdentityFile /path/to/key
Host server2
     HostName server2.com
     User admin
     Port 22
     IdentityFile /path/to/key
```
And when I try to write a an object returned by query method that has been stringified it prints it like this.

````JS
2 [object Object]

Host server2
HostName server2.com
User admin
Port 22
IdentityFile /path/to/key
````

**Comment by dotnil** [comment]
Sorry, wrong example. Should've been:

```js
config[config.length++] = {
    Host: 'test',
    HostName: 'localhost',
    User: 'centos',
    Port: 2000,
    IdentityFile: 'path/to/key/file'
}
```

But `.length` property is currently not writable. So this snippet won't work, yet. 

Anyway, I'll add an `.append` and a `.find` method for appending and finding sections. `.match` can wait.

**Comment by dotnil** [comment]
@simon-p-r ping

**Comment by simon-p-r** [comment]
Looks good, I will test in a few hours

**Comment by simon-p-r** [comment]
I have tested new implementation and they work very well however should query now be removed as find is an enhanced method?

Many thanks
Simon

**Comment by dotnil** [comment]
`.query` is for host config aggregations. There are times we want to find all the configs about certain host. `.query` does exactly that.

`.find` on the other hand, is for finding sections. When you want to read and change ssh config a bit, it's handy. But when it comes to aggregate all the relative configs about some host, it will be way too tedious to do so.

**Comment by simon-p-r** [comment]
Ok no problem, your code style is not something I have not seen before so am learning from it!  

Thank you
Simon

**Comment by dotnil** [comment]
You're welcome. ssh-config 0.2.0 is now release.
