### ISSUE TITLE
Add support for fallback parameters

### ISSUE THREAD

**Issue by derimagia** [dotnil/ssh-config#8]
Right now if this config is parsed and then stringified it loses it's last 2 parameters:

Host *
  # Fallback Identify Files
  IdentityFile ~/.ssh/ids/%h/%r/id_rsa
  IdentityFile ~/.ssh/ids/%h/id_rsa
  IdentityFile ~/.ssh/id_rsa

As far as I know, this is a valid ssh config

Since it's a dict, i'm not sure the best way to handle this. Ideas?

**Comment by dotnil** [comment]
I thought only the first one will be used. Will ssh try all three `IdentityFile` parameters?

**Comment by derimagia** [comment]
Yeah it's pretty neat actually - the first one is used but the file has to exist. So if it doesn't exist it'll move to the next one. Not sure if the way I did it is right with making arrays (If you can think of a better way?).

**Comment by dotnil** [comment]
I think a specific api change is needed. There shall be a major release to resolve this issue. Making the value type as `Array|String` might bring new issues to consumers.

**Comment by dotnil** [comment]
I'll change the data structure a bit to solve #8 and #9. `IdentityFiles` will always be arrays. Comments and white spaces will be stored an the parsed data and there will be a flag to toggle when you `.stringify()`. 

@derimagia How about that?

**Comment by derimagia** [comment]
That sounds good to me!
