### ISSUE TITLE
Feature Request: Metadata

### ISSUE THREAD

**Issue by derimagia** [dotnil/ssh-config#9]
Right now comments are not really dealt with gracefully.

This is a sample input:

```
# This is my website
Host website
  User website
  #Tags tag1
  #Tags tag2
  Port 12335
  HostName 33.33.33.1

Host *
  User defaultuser
  # Enable Connection Sharing
  # ControlMaster auto
  # ControlPath /tmp/ssh_mux_%h_%p_%r
```

This is the current output:

```
# This is my website

Host website
  User website
  #Tags tag2
  Port 12335
  HostName 33.33.33.1

Host *
  User defaultuser
  # ControlPath /tmp/ssh_mux_%h_%p_%r
```

Messing up the comments is not optimal, but I think the we should try to match the input at all times.  Maybe we store the "comment" lines and user's can use that for metadata? Thoughts on this?

**Comment by dotnil** [comment]
Hi @derimagia , with #11 , the comments within config file is now preserved. I'll update the readme to reflect the data structure change swiftly.

**Comment by dotnil** [comment]
1.0.0 is now released. @derimagia care to give it a try?

**Comment by derimagia** [comment]
Sorry for not respawning to this earlier, been busy with other items. Looks good! Out of curiosity, is IdentityFile the only item in ssh config that can be an array or are there others?

**Comment by dotnil** [comment]
Yes, `IdentifyFile` is only option that is allowed to have multiple existences. `Host` and `Match` will open a new section. Options like `Ciphers` can have multiple values separated with comma. For the rest of the options, the first obtained value will be used. 

Oh, I forgot about `CertificateFile`. There can be multiple directives about `CertificateFile` too. Maybe I shall do a patch version asap......

**Comment by dotnil** [comment]
The Readme file has been changed a lot since this is a major version bump. Please give it a read and see if it clarifies your question. Feel free to open new issues if I missed anything.
